eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8600/eureka/
  instance:
    hostname: localhost

spring:
  application:
      name: stock-service-instance